In [ ]:
import pandas as pd 

# Load dataset
df = pd.read_csv("../data/spotify_churn_dataset.csv")

df.head()
#First 5 rows

,user_id,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,1,Female,54,CA,Free,26,23,0.20,Desktop,31,0,1
1,2,Other,33,DE,Family,141,62,0.34,Web,0,1,0
2,3,Male,38,AU,Premium,199,38,0.04,Mobile,0,1,1
3,4,Female,22,CA,Student,36,2,0.31,Mobile,0,1,0
4,5,Other,29,US,Family,250,57,0.36,Mobile,0,1,1

In [ ]:
df.shape
#rows(users), columns(features)

(8000, 12)

In [5]:
df.info

<bound method DataFrame.info of       user_id  gender  age country subscription_type  listening_time  \
0           1  Female   54      CA              Free              26
1           2   Other   33      DE            Family             141
2           3    Male   38      AU           Premium             199
3           4  Female   22      CA           Student              36
4           5   Other   29      US            Family             250
...       ...     ...  ...     ...               ...             ...
7995     7996   Other   44      DE           Student             237
7996     7997    Male   34      AU           Premium              61
7997     7998  Female   17      US              Free              81
7998     7999  Female   34      IN           Student             245
7999     8000   Other   45      AU              Free             210

      songs_played_per_day  skip_rate device_type  ads_listened_per_week  \
0                       23       0.20     Desktop                     31
1                       62       0.34         Web                      0
2                       38       0.04      Mobile                      0
3                        2       0.31      Mobile                      0
4                       57       0.36      Mobile                      0
...                    ...        ...         ...                    ...
7995                    36       0.30      Mobile                      0
7996                    64       0.59      Mobile                      0
7997                    62       0.33     Desktop                      5
7998                    94       0.27     Desktop                      0
7999                    68       0.46     Desktop                      6

      offline_listening  is_churned
0                     0           1
1                     1           0
2                     1           1
3                     1           0
4                     1           1
...                 ...         ...
7995                  1           1
7996                  1           0
7997                  0           0
7998                  1           0
7999                  0           0

[8000 rows x 12 columns]>

In [ ]:
df.isnull().sum()
#check if their is any missing values

user_id                  0
gender                   0
age                      0
country                  0
subscription_type        0
listening_time           0
songs_played_per_day     0
skip_rate                0
device_type              0
ads_listened_per_week    0
offline_listening        0
is_churned               0
dtype: int64

In [ ]:
df.describe()

,user_id,age,listening_time,songs_played_per_day,skip_rate,ads_listened_per_week,offline_listening,is_churned
count,8000.00000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,4000.50000,37.662125,154.068250,50.127250,0.300127,6.943875,0.747750,0.258875
std,2309.54541,12.740359,84.015596,28.449762,0.173594,13.617953,0.434331,0.438044
min,1.00000,16.000000,10.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,2000.75000,26.000000,81.000000,25.000000,0.150000,0.000000,0.000000,0.000000
50%,4000.50000,38.000000,154.000000,50.000000,0.300000,0.000000,1.000000,0.000000
75%,6000.25000,49.000000,227.000000,75.000000,0.450000,5.000000,1.000000,1.000000
max,8000.00000,59.000000,299.000000,99.000000,0.600000,49.000000,1.000000,1.000000

In [9]:
df.columns

Index(['user_id', 'gender', 'age', 'country', 'subscription_type',
       'listening_time', 'songs_played_per_day', 'skip_rate', 'device_type',
       'ads_listened_per_week', 'offline_listening', 'is_churned'],
      dtype='str')